Updating Multiplayer HLAPI Package
Updating the Multiplayer HLAPI package from 1.0.4 to 1.0.6 to fix error:

```Deterministic compilation failed. You can disable Deterministic builds in Player Settings
Library/PackageCache/com.unity.multiplayer-hlapi@1.0.4/Editor/Tools/Weaver/AssemblyInfo.cs(22,28): error CS8357: The specified version string contains wildcards, which are not compatible with determinism. Either remove wildcards from the version string, or disable determinism for this compilation```